version: "3.7"

services:
  app:
    build: .
    ports:
      - 8000:8000
      - 6001:6001
    command: ["./docker-entrypoint.sh"]
    volumes:
      - ./:/app
    environment:
      DB_HOST: postgres
      DB_PASSWORD: secret
      DB_USER: painterly
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - painterly-db:/var/lib/postgres
    environment:
      POSTGRES_USER: painterly
      POSTGRES_PASSWORD: secret

  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  painterly-db:
